USE [PetGame]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Race](
	[RaceId] BIGINT IDENTITY(1,1) UNIQUE NOT NULL,
	[Score] INT NOT NULL,
	[Timestamp] DATETIME NOT NULL,
	[PetId] BIGINT NOT NULL FOREIGN KEY REFERENCES Pet(PetId),
) ON [PRIMARY]
GO